apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfldata-webapp
  labels:
    app: nfldata-webapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfldata-webapp
  template:
    metadata:
      labels:
        app: nfldata-webapp
    spec:
      containers:
      - name: nfldata-api
        image: gcr.io/shadowgraph/nfldata-webapp:local
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 3000
