apiVersion: v1
kind: Service
metadata:
  name: nfldata-api-service
  namespace: default
  labels:
    app: nfldata-api
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: nfldata-api
