apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfldata-webapp
  namespace: default
  labels:
    app: nfldata-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfldata-webapp
  template:
    metadata:
      labels:
        app: nfldata-webapp
    spec:
      containers:
      - image: gcr.io/shadowgraph/github.com/pkukkapalli/nfldata-webapp:latest
        name: nfldata-webapp-container
      - image: gcr.io/shadowgraph/github.com/pkukkapalli/shadowgraph-agent:latest
        name: shadowgraph-agent-container
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP_ADDR
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
